[build]
  publish = "out/"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://api.woke.net/:splat"

[[redirects]]
  from = "/.well-known/matrix/*"
  to = "https://matrix.woke.net/.well-known/matrix/:splat"
  status = 200
